### ISSUE TITLE
Problem with Dockerfile install script

### ISSUE THREAD

**Issue by henryaspegren** [mmmries/roombots#19]
Error trace

Building dependency tree...
Reading state information...
E: Unable to locate package erlang-mini
Removing intermediate container bc0ea160fe8d
       Error while processing push: Error: The command '/bin/sh -c apt-get update && apt-get install -y     tree     curl     unzip     git     ca-certificates     build-essential   && echo "deb http://packages.erlang-solutions.com/debian wheezy contrib" >> /etc/apt/sources.list   && curl 'http://packages.erlang-solutions.com/debian/erlang_solutions.asc' -o 'esolutions.asc'   && apt-key add esolutions.asc   && rm esolutions.asc   && apt-get update   && apt-get install -y --force-yes erlang-mini   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by mmmries** [comment]
@henryaspegren I'm glad to know you tried doing something with roombots! I hope it turns out to be a fun experience despite this error you encountered.

I haven't seen that error before, so I'll go try to run through that process now to see if maybe a version changed upstream that causes it (or more likely I did something wrong 😱 )

**Comment by mmmries** [comment]
@henryaspegren were you trying to build the docker image for the `roombots` website or were you following the instructions to "Make Your Own"? I'm guessing this error occured when you tried to run:

```
$ git push resin master
``` 

Is that right?

**Comment by henryaspegren** [comment]
Hello @mmmries. We are actually a bunch of MIT students designing a lesson built around the iRobot for a school in Korea! I've been using an API to control the robots via a direct connection and was hoping to use a Raspberry pi to control them wirelessly. 

I followed the instructions on this page (the "Make Your Own")
https://roombots.mx.com/make_your_own

For some reason the build has had trouble with the erlang-mini package. I've tried debugging it a whole bunch of ways and can't seem to get it to work. 

Thanks for your help!

**Comment by henryaspegren** [comment]
any chance you'll figure this out?

**Comment by mmmries** [comment]
@henryaspegren I'll definitely take a look at it in the next week. I think it's a problem with the apt repository that erlang solutions makes available.

I'm up against a deadline at work so can't get to it right now, but planning on getting out my pi and doing some debugging over the weekend.

**Comment by mmmries** [comment]
@henryaspegren after some debugging this does appear to be a problem with the apt repository that erlang solutions makes available. I've pushed 3f76d6cbaa2beb0acc703ffdb0efe5c7a4f0a2d0 which has a workaround to install the full-size `erlang` package (rather than the minimal `erlang-mini` package).

This should fix the problem for now so you can get successful builds completed, but hopefully we can switch back to the lighter-weight `erlang-mini` package in the future.
